name: getx_template
version: 1.0.0+1
publish_to: 'none'
description: "A new Flutter project."
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  internet_connection_checker: ^1.0.0+1
  logger: ^2.3.0
  nb_utils: ^7.0.2
  path: any
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path_ios: "assets/images/app_logo.png"
  image_path_android: "assets/images/app_logo.png"
  ios: true
  android: true
  adaptive_icon_background: "#ffffff"
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/db/
    - assets/images/


